# **<font color='orange'><b>Artificial Neural Network (ANN):</b></font>**


# **<font color='orange'><b>Importing libraries-</b></font>**


In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import tensorflow as tf

# **<font color='orange'><b>Check the version of tensorflow-</b></font>**


In [ ]:
tf.__version__  # Check the version of tensorflow

'2.17.0'

# **<font color='orange'><b>Part - 1 Data preprocessing - </b></font>**


# **<font color='orange'><b>Importing dataset-</b></font>**


In [ ]:
data = pd.read_csv("Churn_Modelling.csv")
x = data.iloc[:,3:-1].values # We are starting the input features from the 3 index because this is not much impact on the Deep learning model.
y = data.iloc[:,-1].values

# **<font color='orange'><b>Matrix of features - </b></font>**


In [ ]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


# **<font color='orange'><b>Encoding categorical data - </b></font>**


**Label encoding for the "Gender" column"**

In [ ]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
x[:,2] = Le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# **<font color='orange'><b>OneHotEncoding for "Geography" Column- </b></font>**


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = "passthrough")
x = np.array(ct.fit_transform(x))

# **<font color='orange'><b>Spliting the dataset into training set or testing set-</b></font>**


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

# **<font color='orange'><b>Feature Scaling</b></font>**


In [ ]:
from sklearn.preprocessing import StandardScaler    #Feature scaling is must for building Artificial Neural Network:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# **<font color='orange'><b>Part-2 Building The ANN</b></font>**


**<font color='orange'><b>Initialize the ANN</b></font>**


In [ ]:
ann = tf.keras.models.Sequential()

**<font color='orange'><b>Adding the input layer and first hidden layer:</b></font>**


In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

**<font color='orange'><b>Adding the input layer and second hidden layer:</b></font>**


In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

**<font color='orange'><b>Adding the output layer:</b></font>**


In [ ]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

# **<font color='orange'><b>Part-3 Training the ANN</b></font>**


**<font color='orange'><b>Compiling the ANN</b></font>**


In [ ]:
ann.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])

**<font color='orange'><b>Training the ANN on Training set:</b></font>**


In [ ]:
ann.fit(x_train,y_train,batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.3500 - loss: 0.8340
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7836 - loss: 0.5156
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8014 - loss: 0.4410
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8155 - loss: 0.4312
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8215 - loss: 0.4169
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8249 - loss: 0.4099
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8259 - loss: 0.4084
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8307 - loss: 0.4073
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8295 - loss: 0.4005
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8316 - loss: 0.3929
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8139 - loss: 0.4197
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

# **<font color='orange'><b>Making the prediction and Evaluation the model</b></font>**


# **<font color='orange'><b>Predicting the result for the single observation:</b></font>**


**Use our ANN model to predict if the customer with the following informations will leave the bank:**
- **Geography:Finance:**
- **Credit Score:600:**
- **Gender:Male**
- **Age:40 years old**
- **Tenure: 3 years**
- **Balance:60000 dollar**
- **Number of products:2**
- **Does this customer have a credict card?Yes**
- **Is this customer is an Active member? Yes**
- **Estimated Salary:$50000**
- **So, should we say goodbye to the customer?**

In [ ]:
print(ann.predict(sc.transform([[1, 0 , 0 , 600, 1, 40, 3,60000,2,1,1,50000]]))>0.5)  # Any input inside the predict method must be two dimensional array:


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[False]]


**Here False means we should not say goodbye to the customer:**

# **<font color='orange'><b>Predicting the Test set result:</b></font>**


In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the confusion matrix:**

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1532   63]
 [ 210  195]]


0.8635